version: '3'
services:
  bot:
    build: ./bot
    ports:
      - "1233:1233"
    #Этот инструмент отключает привязку данных к жизненному циклу контейнера, 
    #позволяя получить доступ к контейнерным данным в любой момент. Таким образом, 
    #сделанные в контейнерах записи остаются доступными после уничтожения содержавшего 
    #их контейнера и могут повторно использоваться в других.
    volumes:
      - .bot:/bot
    
    #стартовая команда для запуска контейнера
    command: python ./bot/main.py

    #зависимость от запуска дазы данных
    #сервис db должен запускаться перед bot
    depends_on:
      - db

    env_file:
      - .env
  db:
    image: postgres:14-alpine

